name: LighthouseURLCheck
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: 'https://test-ghactions.herokuapp.com/'
          configPath: './lighthouserc.json'