name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Yarn cause eslint exit with 1, that mean error in npm. Yarn allows you to bypass this
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
          cmd: eslint
